" Checking white spce at the end of line
match Todo /\s\+$/

" Auto indenting on Next Line
set autoindent

" Setting VIM basic color to desert theme
color desert

" Setting 80 lines color column
set cc=80

" Enable Line Number
" set number

" Highlight Matching Brackets
set showmatch

" Search Words with Ignore Case
set ic

" Graphical Menu to cycle through the names of files inside VIM
set wildmenu

" Search as Character is inserted
set incsearch
set hlsearch

" The width of a TAB is set to 4.
" Still it is a \t. It is just that
" Vim will interpret it to be having
" a width of 4.
set tabstop=4

" Indents will have a width of 4
set shiftwidth=4

" Sets the number of columns for a TAB
set softtabstop=4

" Expand TABs to spaces
set expandtab
